#!/bin/bash

#only download two files

HoldList="/home/slag/Escritorio/code/bash/cima/web.txt"

index=0
while read -r line ; do
    ffmpeg -ss 00:50:30 -to 00:50:40 -i "$(youtube-dl -f best --get-url $line)" -c:v copy -c:a copy output-${index}.mp4 </dev/null

    ((index=index+1))
done < "$HoldList"

#ffmpeg -ss 00:50:30 -to 00:51:00 -i "$(youtube-dl -f best --get-url -a $line)" -c:v copy -c:a copy output-${index}.mp4
